steps:
  - name: node:18.19.0
    entrypoint: npm
    args: ["install"]
  - name: node:18.19.0
    entrypoint: npm
    args: ["run", "env:newenv"]
    env:
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - 'FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'
  - name: node:18.19.0
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY